<a href="https://colab.research.google.com/github/Vanessavill/Vanessavill.github.io/blob/PROYECTOS-MACHINE-LEARNING/PROYECTO_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install wooldridge
import wooldridge as wd
import pandas as pd
import numpy as np 
import openpyxl as open
import seaborn as sns
import matplotlib.pyplot as plt
from re import S
from scipy.stats import mode
import statistics as st
from numpy.ma.core import std

     |████████████████████████████████| 5.1 MB 5.0 MB/s 


In [ ]:
BASE= wd.data('crime1')
x= BASE[['pcnv', 'avgsen', 'tottime', 'inc86']]
y= BASE['narr86']
y=y.to_numpy()
x=x.to_numpy()

In [ ]:
x

array([[  0.38      ,  17.60000038,  35.20000076,   0.        ],
       [  0.44      ,   0.        ,   0.        ,   0.80000001],
       [  0.33000001,  22.79999924,  22.79999924,   0.        ],
       ...,
       [  0.        ,   0.        ,   0.        ,   1.89999998],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , 191.30000305]])

In [ ]:
y=y.reshape(-1,1)
y

array([[0],
       [2],
       [1],
       ...,
       [0],
       [1],
       [0]])

In [ ]:
BASE.describe()

narr86      nfarr86      nparr86         pcnv       avgsen  \
count  2725.000000  2725.000000  2725.000000  2725.000000  2725.000000   
mean      0.404404     0.233394     0.125505     0.357787     0.632294   
std       0.859077     0.581014     0.482847     0.395192     3.508031   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.250000     0.000000   
75%       1.000000     0.000000     0.000000     0.670000     0.000000   
max      12.000000     6.000000     8.000000     1.000000    59.200001   

           tottime      ptime86       qemp86        inc86        durat  \
count  2725.000000  2725.000000  2725.000000  2725.000000  2725.000000   
mean      0.838752     0.387156     2.309028    54.967046     2.251376   
std       4.607019     1.950051     1.610428    66.627213     4.607063   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     1.000000     0.400000     0.000000   
50%       0.000000     0.000000     3.000000    29.000000     0.000000   
75%       0.000000     0.000000     4.000000    90.099998     2.000000   
max      63.400002    12.000000     4.000000   541.000000    25.000000   

             black       hispan       born60       pcnvsq       pt86sq  \
count  2725.000000  2725.000000  2725.000000  2725.000000  2725.000000   
mean      0.161101     0.217615     0.362569     0.284131     3.951193   
std       0.367691     0.412700     0.480830     0.390734    22.085840   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.062500     0.000000   
75%       0.000000     0.000000     1.000000     0.448900     0.000000   
max       1.000000     1.000000     1.000000     1.000000   144.000000   

             inc86sq  
count    2725.000000  
mean     7458.932620  
std     16361.238454  
min         0.000000  
25%         0.160000  
50%       841.000000  
75%      8118.009766  
max    292681.000000

In [ ]:
BASE.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2725 entries, 0 to 2724
Data columns (total 16 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   narr86   2725 non-null   int64  
 1   nfarr86  2725 non-null   int64  
 2   nparr86  2725 non-null   int64  
 3   pcnv     2725 non-null   float64
 4   avgsen   2725 non-null   float64
 5   tottime  2725 non-null   float64
 6   ptime86  2725 non-null   int64  
 7   qemp86   2725 non-null   float64
 8   inc86    2725 non-null   float64
 9   durat    2725 non-null   float64
 10  black    2725 non-null   int64  
 11  hispan   2725 non-null   int64  
 12  born60   2725 non-null   int64  
 13  pcnvsq   2725 non-null   float64
 14  pt86sq   2725 non-null   int64  
 15  inc86sq  2725 non-null   float64
dtypes: float64(8), int64(8)
memory usage: 340.8 KB


In [ ]:
matrizx=np.c_[np.ones(2725),x]

In [ ]:
matrizx

array([[  1.        ,   0.38      ,  17.60000038,  35.20000076,
          0.        ],
       [  1.        ,   0.44      ,   0.        ,   0.        ,
          0.80000001],
       [  1.        ,   0.33000001,  22.79999924,  22.79999924,
          0.        ],
       ...,
       [  1.        ,   0.        ,   0.        ,   0.        ,
          1.89999998],
       [  1.        ,   0.        ,   0.        ,   0.        ,
          0.        ],
       [  1.        ,   0.        ,   0.        ,   0.        ,
        191.30000305]])

In [ ]:
X_T=np.transpose(matrizx)

In [ ]:
X_T

array([[  1.        ,   1.        ,   1.        , ...,   1.        ,
          1.        ,   1.        ],
       [  0.38      ,   0.44      ,   0.33000001, ...,   0.        ,
          0.        ,   0.        ],
       [ 17.60000038,   0.        ,  22.79999924, ...,   0.        ,
          0.        ,   0.        ],
       [ 35.20000076,   0.        ,  22.79999924, ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.80000001,   0.        , ...,   1.89999998,
          0.        , 191.30000305]])

In [ ]:
multi1=np.linalg.inv(np.dot(X_T,matrizx))

In [ ]:
multi1

array([[ 9.44299510e-04, -8.41617442e-04, -1.19447995e-05,
        -1.07130690e-05, -4.72408304e-06],
       [-8.41617442e-04,  2.35284094e-03,  3.75881171e-06,
        -8.57221489e-06,  8.39496177e-08],
       [-1.19447995e-05,  3.75881171e-06,  2.16482353e-04,
        -1.53017306e-04,  3.75345021e-08],
       [-1.07130690e-05, -8.57221489e-06, -1.53017306e-04,
         1.25642729e-04,  9.36712152e-08],
       [-4.72408304e-06,  8.39496177e-08,  3.75345021e-08,
         9.36712152e-08,  8.35363644e-08]])

In [ ]:
multi2=np.dot(multi1,X_T)

In [ ]:
multi2

array([[ 3.71563735e-05,  5.70208571e-04,  1.49966359e-04, ...,
         9.35323752e-04,  9.44299510e-04,  4.05824094e-05],
       [-1.83124779e-04,  1.93699726e-04, -1.74925490e-04, ...,
        -8.41457937e-04, -8.41617442e-04, -8.25557880e-04],
       [-1.58663627e-03, -1.02608948e-05,  1.43629861e-03, ...,
        -1.18734839e-05, -1.19447995e-05, -4.76444914e-06],
       [ 1.71554900e-03, -1.44099065e-05, -6.37682238e-04, ...,
        -1.05350937e-05, -1.07130690e-05,  7.20623477e-06],
       [-7.34348090e-07, -4.62031612e-06, -1.70488941e-06, ...,
        -4.56536395e-06, -4.72408304e-06,  1.12564237e-05]])

In [ ]:
multi3=np.dot(multi2,y)

In [ ]:
multi3 #betas
#es la probabilidad de que exista este error, se comete cuando el investigador no rechaza la hipótesis nula siendo esta falsa en la población.

array([[ 0.59387489],
       [-0.16243696],
       [-0.00618803],
       [ 0.00771062],
       [-0.00243615]])

In [ ]:
u=(y-matrizx@multi3)
u

array([[-0.69465347],
       [ 1.47954629],
       [ 0.42501415],
       ...,
       [-0.5892462 ],
       [ 0.40612511],
       [-0.12783923]])

In [ ]:
u_T=u.T
u_T

array([[-0.69465347,  1.47954629,  0.42501415, ..., -0.5892462 ,
         0.40612511, -0.12783923]])

In [ ]:
u_1= (u_T@u)
u_1           #Varianza del error 

array([[1925.92382389]])

In [ ]:
varianza_e=((u_1)/(2725-4-1))
varianza_e

array([[0.70806023]])

In [ ]:
var=(varianza_e*multi1)

In [ ]:
var

array([[ 6.68620927e-04, -5.95915839e-04, -8.45763747e-06,
        -7.58549809e-06, -3.34493532e-06],
       [-5.95915839e-04,  1.66595309e-03,  2.66146508e-06,
        -6.06964444e-06,  5.94413855e-08],
       [-8.45763747e-06,  2.66146508e-06,  1.53282544e-04,
        -1.08345469e-04,  2.65766881e-08],
       [-7.58549809e-06, -6.06964444e-06, -1.08345469e-04,
         8.89626197e-05,  6.63248621e-08],
       [-3.34493532e-06,  5.94413855e-08,  2.65766881e-08,
         6.63248621e-08,  5.91487773e-08]])

In [ ]:
np.diagonal(var)
D=np.sqrt(np.diagonal(var)) #errores estadnar
D #como podemos observar para 0.02585771  al ser el mayor error estándar de la media idica que su estimación menos precisa de la media de la población, 
#en cambio 0.00024321 nos indica una estimación mucho mas precisa

array([0.02585771, 0.04081609, 0.01238073, 0.009432  , 0.00024321])

In [ ]:
multi3.T.squeeze() / D #estadistico T
# en general nos indica el grado de confianza de la diferencia obtenida entre las medias.

array([ 22.9670375 ,  -3.97972866,  -0.49981111,   0.81749603,
       -10.01685265])

In [ ]:
multi3.T.squeeze() + 1.96*D #limite superior de los intervalo 
#Es el valor mayor de cada uno de los intervalos de confianza

array([ 0.64455599, -0.08243742,  0.01807821,  0.02619734, -0.00195947])

In [ ]:
multi3.T.squeeze() - 1.96*D #limite inferior
#Es el valor menor de cada uno de los intervalos de confianza, adicionalmente estos intervalos nos ayudan a detrminar los valores atípicos debido
#a que si estan despues de dichos intervalos se les llama datos atípicos.

array([ 0.54319379, -0.24243649, -0.03045426, -0.0107761 , -0.00291283])

In [ ]:
from operator import index

class regresion():
  def __init__(self,y,x):
    self.x= np.concatenate((np.ones([len(y),1]),x.to_numpy()),axis=1)
    self.y = y.to_numpy().reshape(-1,1)
    self.n= x.shape[0] #numero de observaciones 
    self.k= x.shape[0]-1 #k
    self.X_T= np.tranpose(self.x)

  def betas(self):
      beta=(np.linalg.inv(self.X_T@self.x)@self.X_T@y).reshape(-1,1)
      return beta

      self.sumaxb= self.x@regresion.betas(self) #resultados de x+betas
      self.mediay= np.mean(self,y) #media de y
      self.U= self.y-(self.sumaxb) #residuos 
      self.sec= np.sum(((self.sumaxb)-(self.mediay))**2) #suma explicada de cuadrados 
      self.src= np.sum((self.U)**2) #suma residual de cuadrados 
      self.stc= self.sec + self.src #suma total de cuadrados 
      self.rcuadrado= self.sec/self.stc #R cuadrado

  def gradoslibe (self):
    gl= self.n - self.k #grados de libertad 
    return gl
    
  def covarianza (self):
      cov = (self.src/(regresion.gradoslibe(self)))*(np.linalg.inv((self.X_T@SELF.X)))
      return cov
  
  def varianza(self):
     var= np.diag(regresion.covarianza(self))
     return var



In [ ]:
reg = regresion (self)

NameError: ignored

In [ ]:
class regresion():

  def __init__(self, x): 
    self.x= x
  def mean(self):
    return sum(self.x)/len(self.x)
  def var(self):
    media=sum(self.x)/len(self.x)
    return sum((i-media)**2 for i in self.x)/(len(self.x)-1)
  def std(self):
    return (self.var()**(0.5))
  def coef_var (self):
    return self.std()/self.mean()
  def median(self):
    half = len(self.x)//2
    if not len(self.x) % 2:
      return (self.x[half - 1]+self.x[half]) / 2.0
    return self.x[half]

  def f(x):
    self.reeg= x
    np.random.seed()
    self.y = y.to_numpy().reshape(len(y),1)
    return y
    self.x = x.to_numpy()
    return x
    self.betas = np.linalg.inv(self.x.T@self.x)@self.x.T@self.y
    self.Se= np.linalg .inv(self.x.T@self.x)
    self.t_star= scipy.stats.t.t.ppf(q=1,gl=22)
    def error_e(self):
    error_va = (varianza_e*(np.linalg.inv(np.dot(X_T,matrizx))
     return error_va




$$(X'X)^{-1}X'y$$

In [ ]:
a = 4
b = 5
a + b

In [ ]:
def suma(a,b):
  return a + b

In [ ]:
suma(4,5)

In [ ]:
class Operaciones:

  def __init__(self, a, b):
    self.a = a
    self.b = b

  def suma(self):
    return a + b

In [ ]:
oper = Operaciones(4, 5)

In [ ]:
oper.a

In [ ]:
oper.b

In [ ]:
oper.suma()

In [ ]:
np.linalg.inv(X.T @ X) @ X.T @ y